#%RAML 0.8
title: API Using media type in the URL
baseUri: message://event/listener/message/hearing

version: v1
/hearing.event:
  post:
    body:
        application/vnd.hearing.hearing-initiated+json:
            schema: !include json/schema/hearing.hearing-initiated.json
            example: !include json/hearing.hearing-initiated.json

        application/vnd.hearing.court-assigned+json:
            schema: !include json/schema/hearing.court-assigned.json
            example: !include json/hearing.court-assigned.json

        application/vnd.hearing.room-booked+json:
            schema: !include json/schema/hearing.room-booked.json
            example: !include json/hearing.room-booked.json

        application/vnd.hearing.started+json:
            schema: !include json/schema/hearing.started.json
            example: !include json/hearing.started.json

        application/vnd.hearing.ended+json:
            schema: !include json/schema/hearing.ended.json
            example: !include json/hearing.ended.json

        application/vnd.hearing.case-associated+json:
            schema: !include json/schema/hearing.case-associated.json
            example: !include json/hearing.case-associated.json

        application/vnd.hearing.prosecution-counsel-added+json:
            schema: !include json/schema/hearing.case-associated.json
            example: !include json/hearing.case-associated.json
