#%RAML 0.8
title: Hearing Controller API
baseUri: http://localhost:8080/hearing-query-controller/query/controller/rest/hearing
protocols: [ HTTP, HTTPS ]

/hearings/{hearingId}:
  uriParameters:
        hearingId:
          description: ID of hearing to get
          type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get.hearing+json
            name: hearing.get.hearing
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get.hearing+json:
                    example:  !include json/hearing.get.hearing.json
                    schema:  !include  json/schema/hearing.get.hearing.json


/hearings:
   get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get.hearings-by-startdate+json
            name: hearing.get.hearings-by-startdate
        ...
      queryParameters:
        startDate:
          description: startDate of hearing
          type: string
          required: true


      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get.hearings-by-startdate+json:
                    example:  !include json/hearing.get.hearings.json
                    schema:  !include  json/schema/hearing.get.hearings.json

/hearings/{hearingId}/event-definitions:
    get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.hearing-event-definitions+json
            name: hearing.hearing-event-definitions
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.hearing-event-definitions+json:
                    example:  !include json/hearing.hearing-event-definitions.json
                    schema:   !include json/schema/hearing.hearing-event-definitions.json


/hearing/{hearingId}/prosecution-counsels:
  uriParameters:
        hearingId:
          description: ID of hearing to get the prosecution counsels for
          type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get.prosecution-counsels+json
            name: hearing.get.prosecution-counsels
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get.prosecution-counsels+json:
                    example:  !include json/hearing.get.prosecution-counsels.json
                    schema:  !include  json/schema/hearing.get.prosecution-counsels.json

/hearing/{hearingId}/defence-counsels:
  uriParameters:
        hearingId:
          description: ID of hearing to get the defence counsels for
          type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get.defence-counsels+json
            name: hearing.get.defence-counsels
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get.defence-counsels+json:
                    example:  !include json/hearing.get.defence-counsels.json
                    schema:  !include  json/schema/hearing.get.defence-counsels.json

/hearing/{hearingId}/draft-result:
  uriParameters:
        hearingId:
          description: ID of hearing to get the prosecution counsels for
          type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get-draft-result+json
            name: hearing.get-draft-result
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get-draft-result+json:
                    example:  !include json/hearing.get-draft-result.json
                    schema:  !include  json/schema/hearing.get-draft-result.json