package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import java.util.Arrays;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Query - API - hearing.get.hearings"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get.hearings");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "Judiciary", "Court Associate", "Deputies", "DJMC", "Judge", "CPS", "Non CPS Prosecutors", "Advocates", "Defence Users", "Recorders"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get.hearings-for-today"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get.hearings-for-today");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Magistrates"));
  then
    $outcome.setSuccess(true);
end


rule "Query - API - hearing.get.hearing"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get.hearing");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "Legal Advisers", "System Users", "Judiciary", "Court Associate", "Deputies", "DJMC", "Judge", "Recorders"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get-hearing-event-definitions"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get-hearing-event-definitions");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "Judge", "Deputies", "DJMC", "Judiciary", "Court Associate", "Recorders"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get-active-hearings-for-court-room"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get-active-hearings-for-court-room");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers","Court Associate"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get-hearing-event-definition"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get-hearing-event-definition");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get-hearing-event-log"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get-hearing-event-log");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "Judiciary", "Court Associate", "Deputies", "DJMC", "Judge", "System Users", "Recorders"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get-draft-result"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get-draft-result");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "Legal Advisers", "Judiciary", "Court Associate"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get-results"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get-results");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "Legal Advisers", "Judiciary", "Court Associate"));
  then
    $outcome.setSuccess(true);
end


rule "Query - API - hearing.query.reusable-info"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.query.reusable-info");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "System Users", "Court Clerks", "Legal Advisers", "Court Associate","Judiciary"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.query.search-by-material-id"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.query.search-by-material-id");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"System Users"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.retrieve-subscriptions"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.retrieve-subscriptions");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "Legal Advisers", "System Users", "Court Associate"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get.nows"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get.nows");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get-cracked-ineffective-reason"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get-cracked-ineffective-reason");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.case.timeline"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.case.timeline");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Youth Offending Service Admin", "Probation Admin", "Judiciary", "Listing Officers", "Legal Advisers", "Court Associate", "Court Clerks", "NCES", "CPS", "Court Administrators", "Crown Court Admin", "Judge","Police Admin","DJMC","Deputies", "Victims & Witness Care Admin", "Recorders"))
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.application.timeline"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.application.timeline");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Youth Offending Service Admin", "Probation Admin", "Judiciary", "Listing Officers", "Legal Advisers", "Court Associate", "Court Clerks", "NCES", "CPS", "Court Administrators", "Crown Court Admin", "Judge","Police Admin","DJMC","Deputies", "Victims & Witness Care Admin", "Recorders"))
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.court.list.publish.status"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.court.list.publish.status");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers","Court Clerks", "Legal Advisers","System Users","Court Associate"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.latest-hearings-by-court-centres"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.latest-hearings-by-court-centres");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.hearings-court-centres-for-date"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.hearings-court-centres-for-date");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.defendant.outstanding-fines"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.defendant.outstanding-fines");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers", "Court Associate"));
  then
    $outcome.setSuccess(true);
end


rule "Query - API - hearing.query.session-time"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.query.session-time");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators", "Crown Court Admin"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.defendant.info"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.defendant.info");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.defendant.outstanding-fine-requests"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.defendant.outstanding-fine-requests");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.custody-time-limit"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.custody-time-limit");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "Legal Advisers", "Judiciary", "Court Associate"));
  then
    $outcome.setSuccess(true);
end