package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import java.util.Arrays;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Query - API - hearing.get.hearing"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get.hearing");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "System Users"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get.hearing.v2"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get.hearing.v2");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "System Users"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get.hearings-by-startdate"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get.hearings-by-startdate");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get.hearings-by-startdate.v2"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get.hearings-by-startdate.v2");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get.hearings-by-caseid"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get.hearings-by-caseid");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get-hearing-event-definitions"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get-hearing-event-definitions");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get-hearing-event-definitions.v2"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get-hearing-event-definitions.v2");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get-hearing-event-definition"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get-hearing-event-definition");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get-hearing-event-log"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get-hearing-event-log");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get.prosecution-counsels"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get.prosecution-counsels");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "System Users"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get.defence-counsels"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get.defence-counsels");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "System Users"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get-draft-result"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get-draft-result");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get.case.pleas"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get.case.pleas");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "System Users"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get.case.verdicts"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get.case.verdicts");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "System Users"));
  then
    $outcome.setSuccess(true);
end

rule "Query - API - hearing.get.offences"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.get.offences");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "System Users"));
  then
    $outcome.setSuccess(true);
end
