package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import java.util.Arrays;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - API - Action - hearing.initiate"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.initiate");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "Court Administrators", "Crown Court Admin", "System Users"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.add-prosecution-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.add-prosecution-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.remove-prosecution-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.remove-prosecution-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-prosecution-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-prosecution-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.save-draft-result"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.save-draft-result");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.application-draft-result"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.application-draft-result");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.add-defence-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.add-defence-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.remove-defence-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.remove-defence-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-defence-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-defence-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.share-results"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.share-results");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.create-hearing-event-definitions"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.create-hearing-event-definitions");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "System Users"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.log-hearing-event"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.log-hearing-event");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-hearing-events"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-hearing-events");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.correct-hearing-event"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.correct-hearing-event");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-plea"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-plea");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-verdict"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-verdict");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.generate-nows"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.generate-nows");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-nows-material-status"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-nows-material-status");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.delete-attendee"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.delete-attendee");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.upload-subscriptions"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.upload-subscriptions");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "System Users"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-defendant-attendance-on-hearing-day"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-defendant-attendance-on-hearing-day");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.save-hearing-case-note"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.save-hearing-case-note");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.save-application-response"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.save-application-response");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.add-respondent-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.add-respondent-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.remove-respondent-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.remove-respondent-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-respondent-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-respondent-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.add-applicant-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.add-applicant-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.remove-applicant-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.remove-applicant-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-applicant-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-applicant-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.add-company-representative"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.add-company-representative");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-company-representative"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-company-representative");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.remove-company-representative"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.remove-company-representative");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.add-interpreter-intermediary"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.add-interpreter-intermediary");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-interpreter-intermediary"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-interpreter-intermediary");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.remove-interpreter-intermediary"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.remove-interpreter-intermediary");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.set-trial-type"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.set-trial-type");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers"));
  then
    $outcome.setSuccess(true);
end