package uk.gov.moj.cpp.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import java.util.Arrays;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - API - Action - hearing.initiate"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.initiate");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.add-prosecution-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.add-prosecution-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.save-draft-result"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.save-draft-result");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.add-defence-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.add-defence-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.share-results"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.share-results");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Court Clerks"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.create-hearing-event-definitions"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.create-hearing-event-definitions");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "System Users"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.log-hearing-event"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.log-hearing-event");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-hearing-events"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-hearing-events");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.correct-hearing-event"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.correct-hearing-event");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-plea"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-plea");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-verdict"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-verdict");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.add-update-witness"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.add-update-witness");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.generate-nows"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.generate-nows");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-nows-material-status"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-nows-material-status");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks"));
  then
    $outcome.setSuccess(true);
end