#%RAML 0.8
title: Hearing Command Controller
version: 1.0
baseUri:  message://command/controller/message/hearing

/hearing.controller.command:
  post:
      body:
        application/vnd.hearing.initiate-hearing+json:
            example: !include json/hearing.initiate-hearing.json
            schema:  !include json/schema/hearing.initiate-hearing.json
        application/vnd.hearing.create-hearing-event-definitions+json:
            example: !include json/hearing.create-hearing-event-definitions.json
            schema:  !include json/schema/hearing.create-hearing-event-definitions.json
        application/vnd.hearing.allocate-court+json:
            example: !include json/hearing.allocate-court.json
            schema:  !include json/schema/hearing.allocate-court.json
        application/vnd.hearing.book-room+json:
            example: !include json/hearing.book-room.json
            schema:  !include json/schema/hearing.book-room.json
        application/vnd.hearing.start+json:
            example: !include json/hearing.start.json
            schema:  !include json/schema/hearing.start.json
        application/vnd.hearing.end+json:
            example: !include json/hearing.end.json
            schema:  !include json/schema/hearing.end.json
        application/vnd.hearing.save-draft-result+json:
            example: !include json/hearing.save-draft-result.json
            schema:  !include json/schema/hearing.save-draft-result.json
        application/vnd.hearing.add-case+json:
            example: !include json/hearing.add-case.json
            schema:  !include json/schema/hearing.add-case.json
        application/vnd.hearing.add-prosecution-counsel+json:
            example: !include json/hearing.add-prosecution-counsel.json
            schema:  !include json/schema/hearing.add-prosecution-counsel.json
        application/vnd.hearing.add-defence-counsel+json:
            example: !include json/hearing.add-defence-counsel.json
            schema:  !include json/schema/hearing.add-defence-counsel.json
        application/vnd.hearing.log-hearing-event+json:
            example: !include json/hearing.log-hearing-event.json
            schema: !include json/schema/hearing.log-hearing-event.json
        application/vnd.hearing.correct-hearing-event+json:
            example: !include json/hearing.correct-hearing-event.json
            schema: !include json/schema/hearing.correct-hearing-event.json
        application/vnd.hearing.adjourn-date+json:
            example: !include json/hearing.adjourn-date.json
            schema: !include json/schema/hearing.adjourn-date.json

