#%RAML 0.8
title: Hearing Query view
baseUri: http://localhost:8080/hearing-query-view/query/view/rest/hearing
protocols: [ HTTP, HTTPS ]

/event-definitions:
    get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.hearing-event-definitions+json
            name: hearing.get-hearing-event-definitions
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.hearing-event-definitions+json:
                    example:  !include json/hearing.hearing-event-definitions.json
                    schema:   !include json/schema/hearing.get-hearing-event-definitions.json


/hearings/{hearingId}/event-definitions/{hearingEventDefinitionId}:
  uriParameters:
    hearingId:
      description: ID of the hearing
      type: string
    hearingEventDefinitionId:
      description: ID of hearing event definition
      type: string
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.hearing.hearing-event-definition+json
          name: hearing.get-hearing-event-definition
      ...
    responses:
          200:
              description: OK
              body:
                application/vnd.hearing.hearing-event-definition+json:
                  example:  !include json/hearing.hearing-event-definition.json
                  schema:   !include json/schema/hearing.get-hearing-event-definition.json

/hearings/{hearingId}/draft-result:
  uriParameters:
        hearingId:
          description: ID of hearing to get the draft result
          type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get-draft-result+json
            name: hearing.get-draft-result
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get-draft-result+json:
                    example:  !include json/hearing.get-draft-result.json
                    schema:  !include  json/schema/hearing.get-draft-result.json

/hearings/{hearingId}/application-draft-result:
  uriParameters:
        hearingId:
          description: ID of hearing to get the application draft result
          type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get-application-draft-result+json
            name: hearing.get-application-draft-result
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get-application-draft-result+json:
                    example:  !include json/hearing.get-application-draft-result.json
                    schema:  !include  json/schema/hearing.get-application-draft-result.json

/hearings/{hearingId}/event-log:
    uriParameters:
        hearingId:
            description: ID of hearing to fetch the log for
            type: string
    get:
        description: |
            ...
            (mapping):
                responseType: application/vnd.hearing.hearing-event-log+json
                name: hearing.get-hearing-event-log
            ...
        queryParameters:
            date:
              description: date of hearing
              type: string
              required: true

        responses:
            200:
                description: OK
                body:
                     application/vnd.hearing.hearing-event-log+json:
                        example: !include json/hearing.hearing-event-log.json
                        schema: !include json/schema/hearing.get-hearing-event-log.json

/hearings/{hearingId}/active-hearings-for-court-room/{eventDate}:
    uriParameters:
        hearingId:
            description: ID of hearing to fetch active hearings for court room
            type: string
        eventDate:
            description: ID of hearing to fetch active hearings for court room
            type: string
    get:
        description: |
            ...
            (mapping):
                responseType: application/vnd.hearing.active-hearings-for-court-room+json
                name: hearing.get-active-hearings-for-court-room
            ...
        responses:
            200:
                description: OK
                body:
                     application/vnd.hearing.active-hearings-for-court-room+json:
                        example: !include json/hearing.active-hearings-for-court-room.json
                        schema: !include json/schema/hearing.get-active-hearings-for-court-room.json

/hearings/{hearingId}:
  uriParameters:
        hearingId:
          description: ID of hearing to get
          type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get.hearing+json
            name: hearing.get.hearing

        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get.hearing+json:
                    example:  !include json/hearing.get.hearing.json
                    schema:  !include  json/schema/hearing.get.hearing.json

/hearings:
   get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get.hearings+json
            name: hearing.get.hearings
        ...
      queryParameters:
        date:
          description: date of hearing
          type: string
          required: true
        startTime:
          description: start time
          type: string
          required: false
        endTime:
          description: end time
          type: string
          required: false
        courtCentreId:
          description: court centre id
          type: string
          required: true
        roomId:
          description: room id
          type: string
          required: false

      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get.hearings+json:
                    example:  !include json/hearing.get.hearings.json
                    schema:  !include  json/schema/hearing.get.hearings.json


/hearings-for-today:
   get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get.hearings-for-today+json
            name: hearing.get.hearings-for-today
        ...

      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get.hearings-for-today+json:
                    example:  !include json/hearing.get.hearings-for-today.json
                    schema:  !include  json/schema/hearing.get.hearings-for-today.json

/search:
   get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.query.search-by-material-id+json
            name: hearing.query.search-by-material-id
        ...
      queryParameters:
        q:
          description: query
          type: string
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.query.search-by-material-id+json:
                    example:  !include json/hearing.query.search-by-material-id.json
                    schema:  !include  json/schema/hearing.query.search-by-material-id.json

/retrieve:
    get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.retrieve-subscriptions+json
            name: hearing.retrieve-subscriptions
        ...
      queryParameters:
        referenceDate:
          description: query
          type: string
        nowTypeId:
          description: query
          type: string
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.retrieve-subscriptions+json:
                    example:  !include json/hearing.retrieve-subscriptions.json
                    schema:  !include json/schema/hearing.retrieve-subscriptions.json

/nows/{hearingId}:
  uriParameters:
        hearingId:
          description: ID of hearing to get
          type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get.nows+json
            name: hearing.get.nows
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get.nows+json:
                    example:  !include json/hearing.get.nows.json
                    schema:  !include  json/schema/hearing.get.nows.json



/get-cracked-ineffective-reason:
    get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get-cracked-ineffective-reason+json
            name: hearing.get-cracked-ineffective-reason
        ...
      queryParameters:
        trialTypeId:
          description: query
          type: string
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get-cracked-ineffective-reason+json:
                    example:  !include json/hearing.get-cracked-ineffective-reason.json
                    schema:  !include json/schema/hearing.get-cracked-ineffective-reason.json