#%RAML 0.8
title: Hearing Query view
baseUri: http://localhost:8080/hearing-query-view/query/view/rest/hearing
protocols: [ HTTP, HTTPS ]

/hearings/{hearingId}:
  uriParameters:
        hearingId:
          description: ID of hearing to get
          type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get.hearing+json
            name: hearing.get.hearing
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get.hearing+json:
                    example:  !include json/hearing.get.hearing.json
                    schema:  !include  json/schema/hearing.get.hearing.json

/cases/{caseId}/pleas:
  uriParameters:
        caseId:
          description: get all pleas by caseId
          type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get.case.pleas+json
            name: hearing.get.case.pleas
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get.case.pleas+json:
                    example:  !include json/hearing.get.pleas.json
                    schema:  !include  json/schema/hearing.get.pleas.json

/cases/{caseId}/verdicts:
  uriParameters:
        caseId:
          description: get all verdicts by caseId
          type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get.case.verdicts+json
            name: hearing.get.case.verdicts
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get.case.verdicts+json:
                    example:  !include json/hearing.get.case.verdicts.json
                    schema:  !include  json/schema/hearing.get.case.verdicts.json

/hearings:
   get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get.hearings-by-startdate+json
            name: hearing.get.hearings-by-startdate
        (mapping):
            responseType: application/vnd.hearing.get.hearings-by-caseid+json
            name: hearing.get.hearings-by-caseid
        ...
      queryParameters:
        startDate:
          description: startDate of hearing
          type: string
          required: false
        caseId:
          description: case Id
          type: string
          required: false
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get.hearings-by-startdate+json:
                    example:  !include json/hearing.get.hearings.json
                    schema:  !include  json/schema/hearing.get.hearings.json
                  application/vnd.hearing.get.hearings-by-caseid+json:
                    example:  !include json/hearing.get.hearings.json
                    schema:  !include  json/schema/hearing.get.hearings.json

/hearings/{hearingId}/event-definitions:
    get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.hearing-event-definitions+json
            name: hearing.get-hearing-event-definitions
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.hearing-event-definitions+json:
                    example:  !include json/hearing.hearing-event-definitions.json
                    schema:   !include json/schema/hearing.get-hearing-event-definitions.json


/hearings/{hearingId}/event-definitions/{hearingEventDefinitionId}:
  uriParameters:
    hearingId:
      description: ID of the hearing
      type: string
    hearingEventDefinitionId:
      description: ID of hearing event definition
      type: string
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.hearing.hearing-event-definition+json
          name: hearing.get-hearing-event-definition
      ...
    responses:
          200:
              description: OK
              body:
                application/vnd.hearing.hearing-event-definition+json:
                  example:  !include json/hearing.hearing-event-definition.json
                  schema:   !include json/schema/hearing.get-hearing-event-definition.json

/hearings/{hearingId}/prosecution-counsels:
  uriParameters:
        hearingId:
          description: ID of hearing to get the prosecution counsels for
          type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get.prosecution-counsels+json
            name: hearing.get.prosecution-counsels
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get.prosecution-counsels+json:
                    example:  !include json/hearing.get.prosecution-counsels.json
                    schema:  !include  json/schema/hearing.get.prosecution-counsels.json

/hearings/{hearingId}/defence-counsels:
  uriParameters:
        hearingId:
          description: ID of hearing to get the defence counsels for
          type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get.defence-counsels+json
            name: hearing.get.defence-counsels
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get.defence-counsels+json:
                    example:  !include json/hearing.get.defence-counsels.json
                    schema:  !include  json/schema/hearing.get.defence-counsels.json

/hearings/{hearingId}/draft-result:
  uriParameters:
        hearingId:
          description: ID of hearing to get the draft result
          type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get-draft-result+json
            name: hearing.get-draft-result
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get-draft-result+json:
                    example:  !include json/hearing.get-draft-result.json
                    schema:  !include  json/schema/hearing.get-draft-result.json

/hearings/{hearingId}/event-log:
    uriParameters:
        hearingId:
            description: ID of hearing to fetch the log for
            type: string
    get:
        description: |
            ...
            (mapping):
                responseType: application/vnd.hearing.hearing-event-log+json
                name: hearing.get-hearing-event-log
            ...
        responses:
            200:
                description: OK
                body:
                     application/vnd.hearing.hearing-event-log+json:
                        example: !include json/hearing.hearing-event-log.json
                        schema: !include json/schema/hearing.get-hearing-event-log.json

/hearings/{hearingId}/offences:
    uriParameters:
        hearingId:
            description: ID of hearing to fetch the offences for
            type: string
    get:
        description: |
            ...
            (mapping):
                responseType: application/vnd.hearing.get.offences+json
                name: hearing.get.offences
            ...
        responses:
            200:
                description: OK
                body:
                     application/vnd.hearing.get.offences+json:
                        example: !include json/hearing.get.offences.json
                        schema: !include json/schema/hearing.get.offences.json