#%RAML 0.8
title: Hearing Query view
baseUri: http://localhost:8080/hearing-query-view/query/view/rest/hearing
protocols: [ HTTP, HTTPS ]

/event-definitions:
    get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.hearing-event-definitions+json
            name: hearing.get-hearing-event-definitions
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.hearing-event-definitions+json:
                    example:  !include json/hearing.hearing-event-definitions.json
                    schema:   !include json/schema/hearing.get-hearing-event-definitions.json


/hearings/{hearingId}/event-definitions/{hearingEventDefinitionId}:
  uriParameters:
    hearingId:
      description: ID of the hearing
      type: string
    hearingEventDefinitionId:
      description: ID of hearing event definition
      type: string
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.hearing.hearing-event-definition+json
          name: hearing.get-hearing-event-definition
      ...
    responses:
          200:
              description: OK
              body:
                application/vnd.hearing.hearing-event-definition+json:
                  example:  !include json/hearing.hearing-event-definition.json
                  schema:   !include json/schema/hearing.get-hearing-event-definition.json

/hearings/{hearingId}/draft-result:
  uriParameters:
        hearingId:
          description: ID of hearing to get the draft result
          type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get-draft-result+json
            name: hearing.get-draft-result
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get-draft-result+json:
                    example:  !include json/hearing.get-draft-result.json
                    schema:  !include  json/schema/hearing.get-draft-result.json

/hearings/{hearingId}/event-log:
    uriParameters:
        hearingId:
            description: ID of hearing to fetch the log for
            type: string
    get:
        description: |
            ...
            (mapping):
                responseType: application/vnd.hearing.hearing-event-log+json
                name: hearing.get-hearing-event-log
            ...
        responses:
            200:
                description: OK
                body:
                     application/vnd.hearing.hearing-event-log+json:
                        example: !include json/hearing.hearing-event-log.json
                        schema: !include json/schema/hearing.get-hearing-event-log.json



/hearings/{hearingId}:
  uriParameters:
        hearingId:
          description: ID of hearing to get
          type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get.hearing+json
            name: hearing.get.hearing
        (mapping):
            responseType: application/vnd.hearing.get.nows+json
            name: hearing.get.nows
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get.hearing+json:
                    example:  !include json/hearing.get.hearing.json
                    schema:  !include  json/schema/hearing.get.hearing.json
                  application/vnd.hearing.get.nows+json:
                    example:  !include json/hearing.get.nows.json
                    schema:  !include  json/schema/hearing.get.nows.json

/hearings:
   get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get.hearings-by-date+json
            name: hearing.get.hearings-by-date
        ...
      queryParameters:
        date:
          description: date of hearing
          type: string
          required: false

      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get.hearings-by-date+json:
                    example:  !include json/hearing.get.hearings.json
                    schema:  !include  json/schema/hearing.get.hearings.json

/search:
   get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.query.search-by-material-id+json
            name: hearing.query.search-by-material-id
        ...
      queryParameters:
        q:
          description: query
          type: string
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.query.search-by-material-id+json:
                    example:  !include json/hearing.query.search-by-material-id.json
                    schema:  !include  json/schema/hearing.query.search-by-material-id.json

/retrieve:
    get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.retrieve-subscriptions+json
            name: hearing.retrieve-subscriptions
        ...
      queryParameters:
        referenceDate:
          description: query
          type: string
        nowTypeId:
          description: query
          type: string
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.retrieve-subscriptions+json:
                    example:  !include json/hearing.retrieve-subscriptions.json
                    schema:  !include json/schema/hearing.retrieve-subscriptions.json