#%RAML 0.8
title: Hearing Query API
baseUri: http://localhost:8080/hearing-query-api/query/api/rest/hearing
protocols: [ HTTP, HTTPS ]

/event-definitions:
    get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.hearing-event-definitions+json
            name: hearing.get-hearing-event-definitions
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.hearing-event-definitions+json:
                    example:  !include json/hearing.hearing-event-definitions.json
                    schema:   !include json/schema/hearing.get-hearing-event-definitions.json

/hearings/{hearingId}/event-definitions/{hearingEventDefinitionId}:
  uriParameters:
    hearingId:
      description: ID of the hearing
      type: string
    hearingEventDefinitionId:
      description: ID of hearing event definition
      type: string
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.hearing.hearing-event-definition+json
          name: hearing.get-hearing-event-definition
      ...
    responses:
          200:
              description: OK
              body:
                application/vnd.hearing.hearing-event-definition+json:
                  example:  !include json/hearing.hearing-event-definition.json
                  schema:   !include json/schema/hearing.get-hearing-event-definition.json

/hearings/{hearingId}/draft-result:
  uriParameters:
        hearingId:
          description: ID of hearing to get the draft result
          type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get-draft-result+json
            name: hearing.get-draft-result
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get-draft-result+json:
                    example:  !include json/hearing.get-draft-result.json
                    schema:  !include  json/schema/hearing.get-draft-result.json

/hearings/{hearingId}/event-log:
    uriParameters:
        hearingId:
            description: ID of hearing to fetch the log for
            type: string
    get:
        description: |
            ...
            (mapping):
                responseType: application/vnd.hearing.hearing-event-log+json
                name: hearing.get-hearing-event-log
            ...
        queryParameters:
            date:
              description: date of hearing
              type: string
              required: true

        responses:
            200:
                description: OK
                body:
                     application/vnd.hearing.hearing-event-log+json:
                        example: !include json/hearing.hearing-event-log.json
                        schema: !include json/schema/hearing.get-hearing-event-log.json

/hearings/{hearingId}/active-hearings-for-court-room/{eventDate}:
    uriParameters:
        hearingId:
            description: ID of hearing to fetch active hearings for court room
            type: string
        eventDate:
            description: ID of hearing to fetch active hearings for court room
            type: string
    get:
        description: |
            ...
            (mapping):
                responseType: application/vnd.hearing.active-hearings-for-court-room+json
                name: hearing.get-active-hearings-for-court-room
            ...
        responses:
            200:
                description: OK
                body:
                     application/vnd.hearing.active-hearings-for-court-room+json:
                        example: !include json/hearing.active-hearings-for-court-room.json
                        schema: !include json/schema/hearing.get-active-hearings-for-court-room.json

/hearings/{hearingId}:
  uriParameters:
        hearingId:
          description: ID of hearing to get
          type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get.hearing+json
            name: hearing.get.hearing
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get.hearing+json:
                    example:  !include json/hearing.get.hearing.json
                    schema:  !include  json/schema/hearing.get.hearing.json

/hearings:
   get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get.hearings+json
            name: hearing.get.hearings
        ...
      queryParameters:
        date:
          description: date of hearing
          type: string
          required: true
        startTime:
          description: start time
          type: string
          required: false
        endTime:
          description: end time
          type: string
          required: false
        courtCentreId:
          description: court centre id
          type: string
          required: true
        roomId:
          description: room id
          type: string
          required: false

      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get.hearings+json:
                    example:  !include json/hearing.get.hearings.json
                    schema:  !include  json/schema/hearing.get.hearings.json


/hearings-for-today:
   get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get.hearings-for-today+json
            name: hearing.get.hearings-for-today
        ...

      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get.hearings-for-today+json:
                    example:  !include json/hearing.get.hearings-for-today.json
                    schema:  !include  json/schema/hearing.get.hearings-for-today.json


/search:
   get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.query.search-by-material-id+json
            name: hearing.query.search-by-material-id
        ...
      queryParameters:
        q:
          description: query
          type: string
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.query.search-by-material-id+json:
                    example:  !include json/hearing.query.search-by-material-id.json
                    schema:  !include  json/schema/hearing.query.search-by-material-id.json

/retrieve:
    get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.retrieve-subscriptions+json
            name: hearing.retrieve-subscriptions
        ...
      queryParameters:
        referenceDate:
          description: query
          type: string
        nowTypeId:
          description: query
          type: string
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.retrieve-subscriptions+json:
                    example:  !include json/hearing.retrieve-subscriptions.json
                    schema:  !include json/schema/hearing.retrieve-subscriptions.json

/nows/{hearingId}:
  uriParameters:
        hearingId:
          description: ID of hearing to get
          type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get.nows+json
            name: hearing.get.nows
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get.nows+json:
                    example:  !include json/hearing.get.nows.json
                    schema:  !include  json/schema/hearing.get.nows.json

/get-cracked-ineffective-reason:
    get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get-cracked-ineffective-reason+json
            name: hearing.get-cracked-ineffective-reason
        ...
      queryParameters:
        trialTypeId:
          description: query
          type: string
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get-cracked-ineffective-reason+json:
                    example:  !include json/hearing.get-cracked-ineffective-reason.json
                    schema:  !include json/schema/hearing.get-cracked-ineffective-reason.json

/timeline/{id}:
  uriParameters:
    id:
      description: ID of the case
      type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.case.timeline+json
            name: hearing.case.timeline
        (mapping):
            responseType: application/vnd.hearing.application.timeline+json
            name: hearing.application.timeline
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.case.timeline+json:
                    example:  !include json/hearing.timeline.json
                    schema:  !include json/schema/hearing.timeline.json
                  application/vnd.hearing.application.timeline+json:
                    example:  !include json/hearing.timeline.json
                    schema:  !include json/schema/hearing.timeline.json

/court-list-publish-status/{courtCentreId}:
  description: get status of latest publish court list document
  get:
    description: |
      ...
      (mapping):
          responseType: application/vnd.hearing.court.list.publish.status+json
          name: hearing.court.list.publish.status
      ...
    responses:
      200:
        body:
          application/vnd.hearing.court.list.publish.status+json:
            example:  !include json/hearing.court.list.publish.status.json
            schema:  !include  json/schema/hearing.court.list.publish.status.json

/get-latest-hearings-by-court-centres:
    get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.latest-hearings-by-court-centres+json
            name: hearing.latest-hearings-by-court-centres
        ...
      queryParameters:
        dateOfHearing:
          description: date for which to get hearing.
          type: string
          required: true
        courtCentreIds:
          description: comma separated centre ids.
          type: string
          required: true

      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.latest-hearings-by-court-centres+json:
                     example:  !include json/hearing.get-hearings-by-court-centre.json
                     schema:  !include json/schema/hearing.get-hearings-by-court-centre.json

/hearings/court-centres:
    get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.hearings-court-centres-for-date+json
            name: hearing.hearings-court-centres-for-date
        ...
      queryParameters:
        dateOfHearing:
          description: date for which to get hearing.
          type: string
          required: true
        courtCentreIds:
          description: comma separated centre ids.
          type: string
          required: true

      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.hearings-court-centres-for-date+json:
                    example:  !include json/hearing.get-hearings-by-court-centre.json
                    schema:  !include json/schema/hearing.get-hearings-by-court-centre.json


/defendant/{defendantId}/outstanding-fines:
  uriParameters:
        defendantId:
           description: ID of defendant to query outstanding fines
           type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.defendant.outstanding-fines+json
            name: hearing.defendant.outstanding-fines
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.defendant.outstanding-fines+json:
                    example:  !include json/hearing.defendant.outstanding-fines.json
                    schema:  !include  json/schema/hearing.defendant.outstanding-fines.json


/session-time/{courtHouseId}/{courtRoomId}:
  uriParameters:
    courtHouseId:
      description: ID of the court house
      type: string
    courtRoomId:
          description: ID of the court room
          type: string
  get:
    description: |
      Get recorded Session times:
      ...
      (mapping):
         responseType: application/vnd.hearing.query.session-time+json
         name: hearing.query.session-time
      ...
    queryParameters:
      courtSessionDate:
        description: Court session Date
        type: string
    responses:
          200:
             description: OK
             body:
               application/vnd.hearing.query.session-time+json:
                 schema: !include json/schema/hearing.query.session-time.json
                 example: !include json/hearing.query.session-time.json

/defendant:
   get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.defendant.info+json
            name: hearing.defendant.info
        ...
      queryParameters:
        courtCentreId:
          description: court centre id
          type: string
          required: true
        courtRoomIds:
          description: room id
          type: string
          pattern: (-|\+)?[^,]+
          required: true
        hearingDate:
          description: date of hearing
          type: string
          required: true
          pattern: ^(19|20)\d\d[-](0[1-9]|1[012])[-](0[1-9]|[12][0-9]|3[01])$

      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.defendant.info+json:
                    example:  !include json/hearing.defendant.info.json
                    schema:  !include  json/schema/hearing.defendant.info.json

/defendant-outstanding-fine-requests:
   get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.defendant.outstanding-fine-requests+json
            name: hearing.defendant.outstanding-fine-requests
        ...
      queryParameters:
        hearingDate:
          description: date of hearing
          type: string
          required: true
          pattern: ^(19|20)\d\d[-](0[1-9]|1[012])[-](0[1-9]|[12][0-9]|3[01])$

      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.defendant.outstanding-fine-requests+json:
                    example:  !include json/hearing.defendant.outstanding-fine-requests.json
                    schema:  !include  json/schema/hearing.defendant.outstanding-fine-requests.json

/reusable-info/{hearingId}:
  get:
    description: |
          ...
          (mapping):
              responseType: application/vnd.hearing.query.reusable-info+json
              name: hearing.query.reusable-info
          ...
    queryParameters:
          orderedDate:
              description: date of hearing
              type: string
              required: false
              pattern: ^(19|20)\d\d[-](0[1-9]|1[012])[-](0[1-9]|[12][0-9]|3[01])$

    responses:
              200:
                  description: OK
                  body:
                    application/vnd.hearing.query.reusable-info+json:
                      example:  !include json/hearing.query.reusable-info.json
                      schema:  !include  json/schema/hearing.query.reusable-info.json

