#%RAML 0.8
title: Hearing Query API
baseUri: http://localhost:8080/hearing-query-api/query/api/rest/hearing
protocols: [ HTTP, HTTPS ]
                       
/hearings/{hearingId}:
  uriParameters:
        hearingId:
          description: ID of hearing to get
          type: string
  get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get.hearing+json
            name: hearing.get.hearing
        ...
      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get.hearing+json:
                    example:  !include json/hearing.get.hearing.json
                    schema:  !include  json/schema/hearing.get.hearing.json


/hearings:
   get:
      description: |
        ...
        (mapping):
            responseType: application/vnd.hearing.get.hearings-by-startdate+json
            name: hearing.get.hearings-by-startdate
        ...
      queryParameters:
        startDate:
          description: startDate of hearing
          type: string
          required: true

      responses:
            200:
                description: OK
                body:
                  application/vnd.hearing.get.hearings-by-startdate+json:
                    example:  !include json/hearing.get.hearings.json
                    schema:  !include  json/schema/hearing.get.hearings.json
