#%RAML 0.8
title: API Using media type in the URL
baseUri: message://event/processor/message/hearing

/hearing.event:
  post:
    body:

# Initiate Hearing
        application/vnd.hearing.events.initiated+json:
            schema: !include json/schema/hearing.events.initiated.json
            example: !include json/hearing.events.initiated.json

        application/vnd.hearing.command.lookup-plea-on-offence-for-hearing+json:
            schema: !include json/schema/hearing.command.lookup-plea-on-offence-for-hearing.json
            example: !include json/hearing.command.lookup-plea-on-offence-for-hearing.json

        application/vnd.hearing.command.register-hearing-against-defendant+json:
            example: !include json/hearing.command.register-hearing-against-defendant.json
            schema: !include json/schema/hearing.command.register-hearing-against-defendant.json

        application/vnd.hearing.command.register-hearing-against-case+json:
            example: !include json/hearing.command.register-hearing-against-case.json
            schema: !include json/schema/hearing.command.register-hearing-against-case.json

        application/vnd.hearing.command.lookup-witnesses-on-defendant-for-hearing+json:
             example: !include json/hearing.command.lookup-witnesses-on-defendant-for-hearing.json
             schema: !include json/schema/hearing.command.lookup-witnesses-on-defendant-for-hearing.json

# Inherit Plea after Initiate Hearing
        application/vnd.hearing.events.found-plea-for-hearing-to-inherit+json:
            schema: !include json/schema/hearing.events.found-plea-for-hearing-to-inherit.json
            example: !include json/hearing.events.found-plea-for-hearing-to-inherit.json

        application/vnd.hearing.command.update-hearing-with-inherited-plea+json:
            schema: !include json/schema/hearing.command.update-hearing-with-inherited-plea.json
            example: !include json/hearing.command.update-hearing-with-inherited-plea.json

# Sending Sheet Complete
        application/vnd.hearing.record-sending-sheet-complete+json:
            example: !include json/hearing.record-sending-sheet-complete.json
            schema:  !include json/schema/hearing.record-sending-sheet-complete.json

        application/vnd.hearing.sending-sheet-recorded+json:
            schema: !include json/schema/hearing.sending-sheet-recorded.json
            example: !include json/hearing.sending-sheet-recorded.json

        application/vnd.hearing.record-mags-court-hearing+json:
            schema: !include json/schema/hearing.record-mags-court-hearing.json
            example: !include json/hearing.record-mags-court-hearing.json

        application/vnd.hearing.mags-court-hearing-recorded+json:
            schema: !include json/schema/hearing.mags-court-hearing-recorded.json
            example: !include json/hearing.mags-court-hearing-recorded.json

# Log Event
        application/vnd.hearing.hearing-event-logged+json:
            schema: !include json/schema/hearing.hearing-event-logged.json
            example: !include json/hearing.hearing-event-logged.json

        application/vnd.hearing.hearing-event-ignored+json:
            schema: !include json/schema/hearing.hearing-event-ignored.json
            example: !include json/hearing.hearing-event-ignored.json
        application/vnd.hearing.hearing-events-updated+json:
            schema: !include json/schema/hearing.hearing-events-updated.json
            example: !include json/hearing.hearing-events-updated.json			

# Update Plea
        application/vnd.hearing.hearing-plea-updated+json:
            schema: !include json/schema/hearing.hearing-plea-updated.json
            example: !include json/hearing.hearing-plea-updated.json
        application/vnd.hearing.hearing-update-plea-ignored+json:
            schema: !include json/schema/hearing.hearing-update-plea-ignored.json
            example: !include json/hearing.hearing-update-plea-ignored.json

# Update Offence Aggregate with Plea
        application/vnd.hearing.hearing-offence-plea-updated+json:
            schema: !include json/schema/hearing.hearing-offence-plea-updated.json
            example: !include json/hearing.hearing-offence-plea-updated.json

# Witness-added
        application/vnd.hearing.events.witness-added+json:
            schema: !include json/schema/hearing.events.witness-added.json
            example: !include json/hearing.events.witness-added.json

# Conviction Date
        application/vnd.hearing.conviction-date-added+json:
            schema: !include json/schema/hearing.conviction-date-added.json
            example: !include json/hearing.conviction-date-added.json

        application/vnd.hearing.conviction-date-removed+json:
            schema: !include json/schema/hearing.conviction-date-removed.json
            example: !include json/hearing.conviction-date-removed.json

# Share Results
        application/vnd.hearing.results-shared+json:
            schema: !include json/schema/hearing.results-shared.json
            example: !include json/hearing.results-shared.json

# Save Draft Results
        application/vnd.hearing.draft-result-saved+json:
            schema: !include json/schema/hearing.draft-result-saved.json
            example: !include json/hearing.draft-result-saved.json

# Update Verdict
        application/vnd.hearing.offence-verdict-updated+json:
            schema: !include json/schema/hearing.offence-verdict-updated.json
            example: !include json/hearing.offence-verdict-updated.json

# Case Defendant Details Change
        application/vnd.hearing.update-case-defendant-details-enriched-with-hearing-ids+json:
            example: !include json/hearing.update-case-defendant-details-enriched-with-hearing-ids.json
            schema: !include json/schema/hearing.update-case-defendant-details-enriched-with-hearing-ids.json

        application/vnd.hearing.update-case-defendant-details-against-hearing-aggregate+json:
            example: !include json/hearing.update-case-defendant-details-against-hearing-aggregate.json
            schema: !include json/schema/hearing.update-case-defendant-details-against-hearing-aggregate.json

        application/vnd.hearing.update-case-defendant-details+json:
            schema: !include json/schema/hearing.update-case-defendant-details.json
            example: !include json/hearing.update-case-defendant-details.json

# Case Defendant Offences Change
        application/vnd.hearing.events.found-hearings-for-new-offence+json:
            example: !include json/hearing.events.found-hearings-for-new-offence.json
            schema: !include json/schema/hearing.events.found-hearings-for-new-offence.json

        application/vnd.hearing.command.add-new-offence-to-hearings+json:
            example: !include json/hearing.command.add-new-offence-to-hearings.json
            schema: !include json/schema/hearing.command.add-new-offence-to-hearings.json

        application/vnd.hearing.events.found-hearings-for-edit-offence+json:
            example: !include json/hearing.events.found-hearings-for-edit-offence.json
            schema: !include json/schema/hearing.events.found-hearings-for-edit-offence.json

        application/vnd.hearing.command.update-offence-on-hearings+json:
            example: !include json/hearing.command.update-offence-on-hearings.json
            schema: !include json/schema/hearing.command.update-offence-on-hearings.json

        application/vnd.hearing.events.found-hearings-for-delete-offence+json:
            example: !include json/hearing.events.found-hearings-for-delete-offence.json
            schema: !include json/schema/hearing.events.found-hearings-for-delete-offence.json

        application/vnd.hearing.command.delete-offence-on-hearings+json:
            example: !include json/hearing.command.delete-offence-on-hearings.json
            schema: !include json/schema/hearing.command.delete-offence-on-hearings.json

# Nows
        application/vnd.hearing.events.nows-material-status-updated+json:
            schema: !include json/schema/hearing.events.nows-material-status-updated.json
            example: !include json/hearing.events.nows-material-status-updated.json
        application/vnd.hearing.events.nows-requested+json:
            schema: !include json/schema/hearing.events.nows-requested.json
            example: !include json/hearing.events.nows-requested.json

# Attendees
        application/vnd.hearing.events.attendee-deleted+json:
            schema: !include json/schema/hearing.events.attendee-deleted.json
            example: !include json/hearing.events.attendee-deleted.json

/public.event:
  post:
    body:
# Initiate Mags Court Hearing
        application/vnd.public.progression.events.sending-sheet-completed+json:
                schema: !include json/schema/public.progression.events.sending-sheet-completed.json
                example: !include json/public.progression.events.sending-sheet-completed.json

# Case Defendant Details Change
        application/vnd.public.progression.case-defendant-changed+json:
                schema: !include json/schema/public.progression.case-defendant-changed.json
                example: !include json/public.progression.case-defendant-changed.json

# Case Defendant Offences Changed
        application/vnd.public.progression.defendant-offences-changed+json:
                schema: !include json/schema/public.progression.defendant-offences-changed.json
                example: !include json/public.progression.defendant-offences-changed.json
# Material upload
        application/vnd.material.material-added+json:
                schema: !include json/schema/material.material-added.json
                example: !include json/material.material-added.json
        application/vnd.public.hearing.events.nows-material-status-updated+json:
                schema: !include json/schema/public.hearing.events.nows-material-status-updated.json
                example: !include json/public.hearing.events.nows-material-status-updated.json				
        application/vnd.public.resultinghmps.event.nows-material-status-updated+json:
                schema: !include json/schema/public.resultinghmps.event.nows-material-status-updated.json
                example: !include json/public.resultinghmps.event.nows-material-status-updated.json				