#%RAML 0.8
title: API Using media type in the URL
baseUri: message://event/processor/message/hearing

/hearing.event:
  post:
    body:
        application/vnd.hearing.hearing-initiated+json:
            schema: !include json/schema/hearing.hearing-initiated.json
            example: !include json/hearing.hearing-initiated.json
        application/vnd.hearing.adjourn-date-updated+json:
            schema: !include json/schema/hearing.adjourn-date-updated.json
            example: !include json/hearing.adjourn-date-updated.json
        application/vnd.hearing.results-shared+json:
            schema: !include json/schema/hearing.results-shared.json
            example: !include json/hearing.results-shared.json
        application/vnd.hearing.result-amended+json:
            schema: !include json/schema/hearing.result-amended.json
            example: !include json/hearing.result-amended.json
        application/vnd.hearing.hearing-event-logged+json:
            schema: !include json/schema/hearing.hearing-event-logged.json
            example: !include json/hearing.hearing-event-logged.json
        application/vnd.hearing.confirmed-recorded+json:
            schema: !include json/schema/hearing.confirmed-recorded.json
            example: !include json/hearing.confirmed-recorded.json
        application/vnd.hearing.case.plea-added+json:
            schema: !include json/schema/hearing.case.plea-added.json
            example: !include json/hearing.case.plea-added.json
        application/vnd.hearing.case.plea-changed+json:
            schema: !include json/schema/hearing.case.plea-changed.json
            example: !include json/hearing.case.plea-changed.json

/public.event:
  post:
    body:
        application/vnd.public.hearing-confirmed+json:
            schema: !include json/schema/public.hearing-confirmed.json
            example: !include json/public.hearing-confirmed.json
