#%RAML 0.8
title: API Using media type in the URL
baseUri: message://event/processor/message/hearing

/public.event:
  get:
      responses:
          200:
              body:
# Initiate Hearing
                  application/vnd.public.hearing.initiated+json:
                      schema: !include json/schema/public.hearing.initiated.json
                      example: !include json/public.hearing.initiated.json

# Initiate Mags Court Hearing
                  application/vnd.public.mags.hearing.initiated+json:
                      schema: !include json/schema/public.mags.hearing.initiated.json
                      example: !include json/public.mags.hearing.initiated.json

# Events
                  application/vnd.public.hearing.event-logged+json:
                      schema: !include json/schema/public.hearing.event-logged.json
                      example: !include json/public.hearing.event-logged.json
                  application/vnd.public.hearing.event-ignored+json:
                      schema: !include json/schema/public.hearing.event-ignored.json
                      example: !include json/public.hearing.event-ignored.json
                  application/vnd.public.hearing.event-timestamp-corrected+json:
                      schema: !include json/schema/public.hearing.event-timestamp-corrected.json
                      example: !include json/public.hearing.event-timestamp-corrected.json
                  application/vnd.public.hearing.events-updated+json:
                      schema: !include json/schema/public.hearing.events-updated.json
                      example: !include json/public.hearing.events-updated.json           

# Resulting
                  application/vnd.public.hearing.resulted+json:
                      schema: !include json/schema/public.hearing.resulted.json
                      example: !include json/public.hearing.resulted.json
                  application/vnd.public.hearing.draft-result-saved+json:
                      schema: !include json/schema/public.hearing.draft-result-saved.json
                      example: !include json/public.hearing.draft-result-saved.json

# Pleas
                  application/vnd.public.hearing.plea-updated+json:
                      schema: !include json/schema/public.hearing.plea-updated.json
                      example: !include json/public.hearing.plea-updated.json
                  application/vnd.public.hearing.update-plea-ignored+json:
                      schema: !include json/schema/public.hearing.update-plea-ignored.json
                      example: !include json/public.hearing.update-plea-ignored.json

# Verdicts
                  application/vnd.public.hearing.verdict-updated+json:
                      schema: !include json/schema/public.hearing.verdict-updated.json
                      example: !include json/public.hearing.verdict-updated.json

# Conviction Date
                  application/vnd.public.hearing.offence-conviction-date-changed+json:
                      schema: !include json/schema/public.hearing.offence-conviction-date-changed.json
                      example: !include json/public.hearing.offence-conviction-date-changed.json
                  application/vnd.public.hearing.offence-conviction-date-removed+json:
                      schema: !include json/schema/public.hearing.offence-conviction-date-removed.json
                      example: !include json/public.hearing.offence-conviction-date-removed.json

# Nows
                  application/vnd.public.hearing.events.nows-material-status-updated+json:
                      schema: !include json/schema/public.hearing.events.nows-material-status-updated.json
                      example: !include json/public.hearing.events.nows-material-status-updated.json
                  application/vnd.public.hearing.events.nows-requested+json:
                      schema: !include json/schema/public.hearing.events.nows-requested.json
                      example: !include json/public.hearing.events.nows-requested.json
                  application/vnd.public.hearing.events.notification-id-generated+json:
                      schema: !include json/schema/public.hearing.events.notification-id-generated.json
                      example: !include json/public.hearing.events.notification-id-generated.json

# Attendees
                  application/vnd.public.hearing.events.attendee-deleted+json:
                      schema: !include json/schema/public.hearing.events.attendee-deleted.json
                      example: !include json/public.hearing.events.attendee-deleted.json

# Hearing Adjourned
                  application/vnd.public.hearing.adjourned+json:
                      schema: !include json/schema/public.hearing.adjourned.json
                      example: !include json/public.hearing.adjourned.json
