#%RAML 0.8
title: API Using media type in the URL
baseUri: message://event/processor/message/hearing

/public.event:
  get:
      responses:
          200:
              body:
                  application/vnd.public.hearing.resulted+json:
                      schema: !include json/schema/public.hearing.resulted.json
                      example: !include json/public.hearing.resulted.json
                  application/vnd.public.hearing.result-amended+json:
                      schema: !include json/schema/public.hearing.result-amended.json
                      example: !include json/public.hearing.result-amended.json
                  application/vnd.public.hearing.event-logged+json:
                      schema: !include json/schema/public.hearing.event-logged.json
                      example: !include json/public.hearing.event-logged.json
                  application/vnd.public.hearing.event-timestamp-corrected+json:
                      schema: !include json/schema/public.hearing.event-timestamp-corrected.json
                      example: !include json/public.hearing.event-timestamp-corrected.json
                  application/vnd.public.hearing.plea-updated+json:
                      schema: !include json/schema/public.hearing.plea-updated.json
                      example: !include json/public.hearing.plea-updated.json
                  application/vnd.public.hearing.update-plea-ignored+json:
                      schema: !include json/schema/public.hearing.update-plea-ignored.json
                      example: !include json/public.hearing.update-plea-ignored.json
