#%RAML 0.8
title: Hearing API
baseUri:  http://localhost:8080/hearing-command-api/command/api/rest/hearing


/hearings:
    post:
      description: |
        ...
        (mapping):
            requestType: application/vnd.hearing.initiate+json
            name: hearing.initiate
        ...
      body:
        application/vnd.hearing.initiate+json:
            example:
             !include json/hearing.initiate.json
            schema:
             !include json/schema/hearing.initiate.json
      responses:
            202:
                description: OK

/hearings/{hearingId}:
  displayName: Hearing
  post:
      description: |
        ...
        (mapping):
            requestType: application/vnd.hearing.add-prosecution-counsel+json
            name: hearing.add-prosecution-counsel
        (mapping):
            requestType: application/vnd.hearing.add-defence-counsel+json
            name: hearing.add-defence-counsel
        (mapping):
            requestType: application/vnd.hearing.save-draft-result+json
            name: hearing.save-draft-result
        (mapping):
            requestType: application/vnd.hearing.update-plea+json
            name: hearing.update-plea
        (mapping):
            requestType: application/vnd.hearing.update-verdict+json
            name: hearing.update-verdict
        ...
      body:
        application/vnd.hearing.save-draft-result+json:
            example:
             !include json/hearing.save-draft-result.json
            schema:
             !include json/schema/hearing.save-draft-result.json
        application/vnd.hearing.add-prosecution-counsel+json:
            example:
             !include json/hearing.add-prosecution-counsel.json
            schema:
             !include json/schema/hearing.add-prosecution-counsel.json
        application/vnd.hearing.add-defence-counsel+json:
            example:
             !include json/hearing.add-defence-counsel.json
            schema:
             !include json/schema/hearing.add-defence-counsel.json
        application/vnd.hearing.update-plea+json:
            example:
             !include json/hearing.update-plea.json
            schema:
             !include json/schema/hearing.update-plea.json
        application/vnd.hearing.update-verdict+json:
            example:
             !include json/hearing.update-verdict.json
            schema:
             !include json/schema/hearing.update-verdict.json
      responses:
            202:
                description: OK

/hearings/event-definitions:
    post:
      description: |
        ...
        (mapping):
            requestType: application/vnd.hearing.create-hearing-event-definitions+json
            name: hearing.create-hearing-event-definitions
        ...
      body:
        application/vnd.hearing.create-hearing-event-definitions+json:
            example:
             !include json/hearing.create-hearing-event-definitions.json
            schema:
             !include json/schema/hearing.create-hearing-event-definitions.json
      responses:
            202:
                description: OK

/hearings/{hearingId}/event:
  post:
      description: |
        ...
        (mapping):
            requestType: application/vnd.hearing.log-hearing-event+json
            name: hearing.log-hearing-event
        ...
      body:
        application/vnd.hearing.log-hearing-event+json:
            example: !include json/hearing.log-hearing-event.json
            schema: !include json/schema/hearing.log-hearing-event.json
      responses:
            202:
                description: OK

/hearings/{hearingId}/event/{hearingEventId}:
  post:
      description: |
        ...
        (mapping):
            requestType: application/vnd.hearing.correct-hearing-event+json
            name: hearing.correct-hearing-event
        ...
      body:
        application/vnd.hearing.correct-hearing-event+json:
            example: !include json/hearing.correct-hearing-event.json
            schema: !include json/schema/hearing.correct-hearing-event.json
      responses:
            202:
                description: OK

/hearings/{hearingId}/share-results:
  post:
      description: |
        ...
        (mapping):
            requestType: application/vnd.hearing.share-results+json
            name: hearing.share-results
        ...
      body:
        application/vnd.hearing.share-results+json:
            example: !include json/hearing.share-results.json
            schema: !include json/schema/hearing.share-results.json
      responses:
            202:
                description: OK
