#%RAML 0.8
title: Hearing API
baseUri:  http://localhost:8080/hearing-command-api/command/api/rest/hearing


/hearings:
    post:
      description: |
        ...
        (mapping):
            requestType: application/vnd.hearing.initiate+json
            name: hearing.initiate
        (mapping):
            requestType: application/vnd.hearing.generate-nows+json
            name: hearing.generate-nows
        (mapping):
            requestType: application/vnd.hearing.update-defendant-attendance-on-hearing-day+json
            name: hearing.update-defendant-attendance-on-hearing-day
        ...
      body:
        application/vnd.hearing.initiate+json:
            example:
             !include json/hearing.initiate.json
            schema:
             !include json/schema/hearing.initiate.json
        application/vnd.hearing.generate-nows+json:
            example:
             !include json/hearing.generate-nows.json
            schema:
             !include json/schema/hearing.generate-nows.json
        application/vnd.hearing.update-defendant-attendance-on-hearing-day+json:
            example:
             !include json/hearing.update-defendant-attendance-on-hearing-day.json
            schema:
             !include json/schema/hearing.update-defendant-attendance-on-hearing-day.json
      responses:
            202:
                description: OK

/hearings/{hearingId}:
  displayName: Hearing
  post:
      description: |
        ...
        (mapping):
            requestType: application/vnd.hearing.add-prosecution-counsel+json
            name: hearing.add-prosecution-counsel
        (mapping):
            requestType: application/vnd.hearing.remove-prosecution-counsel+json
            name: hearing.remove-prosecution-counsel
        (mapping):
            requestType: application/vnd.hearing.update-prosecution-counsel+json
            name: hearing.update-prosecution-counsel
        (mapping):
            requestType: application/vnd.hearing.add-defence-counsel+json
            name: hearing.add-defence-counsel
        (mapping):
            requestType: application/vnd.hearing.remove-defence-counsel+json
            name: hearing.remove-defence-counsel
        (mapping):
            requestType: application/vnd.hearing.update-defence-counsel+json
            name: hearing.update-defence-counsel
        (mapping):
            requestType: application/vnd.hearing.save-draft-result+json
            name: hearing.save-draft-result
        (mapping):
            requestType: application/vnd.hearing.update-plea+json
            name: hearing.update-plea
        (mapping):
            requestType: application/vnd.hearing.update-verdict+json
            name: hearing.update-verdict
        (mapping):
            requestType: application/vnd.hearing.save-hearing-case-note+json
            name: hearing.save-hearing-case-note
        (mapping):
            requestType: application/vnd.hearing.save-application-response+json
            name: hearing.save-application-response
        (mapping):
            requestType: application/vnd.hearing.add-respondent-counsel+json
            name: hearing.add-respondent-counsel
        (mapping):
            requestType: application/vnd.hearing.remove-respondent-counsel+json
            name: hearing.remove-respondent-counsel
        (mapping):
            requestType: application/vnd.hearing.update-respondent-counsel+json
            name: hearing.update-respondent-counsel
        (mapping):
            requestType: application/vnd.hearing.add-applicant-counsel+json
            name: hearing.add-applicant-counsel
        (mapping):
            requestType: application/vnd.hearing.remove-applicant-counsel+json
            name: hearing.remove-applicant-counsel
        (mapping):
            requestType: application/vnd.hearing.update-applicant-counsel+json
            name: hearing.update-applicant-counsel
        (mapping):
            requestType: application/vnd.hearing.add-company-representative+json
            name: hearing.add-company-representative
        (mapping):
            requestType: application/vnd.hearing.update-company-representative+json
            name: hearing.update-company-representative
        (mapping):
            requestType: application/vnd.hearing.remove-company-representative+json
            name: hearing.remove-company-representative
        (mapping):
            requestType: application/vnd.hearing.add-interpreter-intermediary+json
            name: hearing.add-interpreter-intermediary
        (mapping):
            requestType: application/vnd.hearing.update-interpreter-intermediary+json
            name: hearing.update-interpreter-intermediary
        (mapping):
            requestType: application/vnd.hearing.remove-interpreter-intermediary+json
            name: hearing.remove-interpreter-intermediary
        (mapping):
            requestType: application/vnd.hearing.set-trial-type+json
            name: hearing.set-trial-type
        ...
      body:
        application/vnd.hearing.save-draft-result+json:
            example:
             !include json/hearing.save-draft-result.json
            schema:
             !include json/schema/hearing.save-draft-result.json
        application/vnd.hearing.add-prosecution-counsel+json:
            example:
             !include json/hearing.add-prosecution-counsel.json
            schema:
             !include json/schema/hearing.add-prosecution-counsel.json
        application/vnd.hearing.remove-prosecution-counsel+json:
            example:
             !include json/hearing.remove-prosecution-counsel.json
            schema:
             !include json/schema/hearing.remove-prosecution-counsel.json
        application/vnd.hearing.update-prosecution-counsel+json:
            example:
              !include json/hearing.update-prosecution-counsel.json
            schema:
              !include json/schema/hearing.update-prosecution-counsel.json
        application/vnd.hearing.add-defence-counsel+json:
            example:
             !include json/hearing.add-defence-counsel.json
            schema:
             !include json/schema/hearing.add-defence-counsel.json
        application/vnd.hearing.remove-defence-counsel+json:
            example:
             !include json/hearing.remove-defence-counsel.json
            schema:
             !include json/schema/hearing.remove-defence-counsel.json
        application/vnd.hearing.update-defence-counsel+json:
            example:
             !include json/hearing.update-defence-counsel.json
            schema:
             !include json/schema/hearing.update-defence-counsel.json
        application/vnd.hearing.update-plea+json:
            example:
             !include json/hearing.update-plea.json
            schema:
             !include json/schema/hearing.update-plea.json
        application/vnd.hearing.update-verdict+json:
            example:
             !include json/hearing.update-verdict.json
            schema:
             !include json/schema/hearing.update-verdict.json
        application/vnd.hearing.save-hearing-case-note+json:
            example: !include json/hearing.save-hearing-case-note.json
            schema: !include json/schema/hearing.save-hearing-case-note.json
        application/vnd.hearing.save-application-response+json:
            example: !include json/hearing.save-application-response.json
            schema: !include json/schema/hearing.save-application-response.json
        application/vnd.hearing.add-respondent-counsel+json:
            example: !include json/hearing.add-respondent-counsel.json
            schema:  !include json/schema/hearing.add-respondent-counsel.json
        application/vnd.hearing.remove-respondent-counsel+json:
            example: !include json/hearing.remove-respondent-counsel.json
            schema:  !include json/schema/hearing.remove-respondent-counsel.json
        application/vnd.hearing.update-respondent-counsel+json:
            example: !include json/hearing.update-respondent-counsel.json
            schema:  !include json/schema/hearing.update-respondent-counsel.json
        application/vnd.hearing.add-applicant-counsel+json:
            example: !include json/hearing.add-applicant-counsel.json
            schema:  !include json/schema/hearing.add-applicant-counsel.json
        application/vnd.hearing.remove-applicant-counsel+json:
            example: !include json/hearing.remove-applicant-counsel.json
            schema:  !include json/schema/hearing.remove-applicant-counsel.json
        application/vnd.hearing.update-applicant-counsel+json:
            example: !include json/hearing.update-applicant-counsel.json
            schema:  !include json/schema/hearing.update-applicant-counsel.json
        application/vnd.hearing.add-company-representative+json:
            example: !include json/hearing.add-company-representative.json
            schema:  !include json/schema/hearing.add-company-representative.json
        application/vnd.hearing.update-company-representative+json:
            example: !include json/hearing.update-company-representative.json
            schema:  !include json/schema/hearing.update-company-representative.json
        application/vnd.hearing.remove-company-representative+json:
            example: !include json/hearing.remove-company-representative.json
            schema:  !include json/schema/hearing.remove-company-representative.json
        application/vnd.hearing.add-interpreter-intermediary+json:
            example: !include json/hearing.add-interpreter-intermediary.json
            schema:  !include json/schema/hearing.add-interpreter-intermediary.json
        application/vnd.hearing.update-interpreter-intermediary+json:
            example: !include json/hearing.update-interpreter-intermediary.json
            schema:  !include json/schema/hearing.update-interpreter-intermediary.json
        application/vnd.hearing.remove-interpreter-intermediary+json:
            example: !include json/hearing.remove-interpreter-intermediary.json
            schema:  !include json/schema/hearing.remove-interpreter-intermediary.json
        application/vnd.hearing.set-trial-type+json:
            example: !include json/hearing.set-trial-type.json
            schema: !include json/schema/hearing.set-trial-type.json
      responses:
            202:
                description: OK

/hearings/event-definitions:
    post:
      description: |
        ...
        (mapping):
            requestType: application/vnd.hearing.create-hearing-event-definitions+json
            name: hearing.create-hearing-event-definitions
        ...
      body:
        application/vnd.hearing.create-hearing-event-definitions+json:
            example:
             !include json/hearing.create-hearing-event-definitions.json
            schema:
             !include json/schema/hearing.create-hearing-event-definitions.json
      responses:
            202:
                description: OK

/hearings/{hearingId}/event:
  post:
      description: |
        ...
        (mapping):
            requestType: application/vnd.hearing.log-hearing-event+json
            name: hearing.log-hearing-event
        ...
      body:
        application/vnd.hearing.log-hearing-event+json:
            example: !include json/hearing.log-hearing-event.json
            schema: !include json/schema/hearing.log-hearing-event.json
      responses:
            202:
              description: OK

/hearings/{hearingId}/events:
  post:
      description: |
        ...
        (mapping):
            requestType: application/vnd.hearing.update-hearing-events+json
            name: hearing.update-hearing-events	
        ...
      body:
        application/vnd.hearing.update-hearing-events+json:
            example: !include json/hearing.update-hearing-events.json
            schema: !include json/schema/hearing.update-hearing-events.json			
      responses:
            202:
                description: OK

/hearings/{hearingId}/event/{hearingEventId}:
  post:
      description: |
        ...
        (mapping):
            requestType: application/vnd.hearing.correct-hearing-event+json
            name: hearing.correct-hearing-event
        ...
      body:
        application/vnd.hearing.correct-hearing-event+json:
            example: !include json/hearing.correct-hearing-event.json
            schema: !include json/schema/hearing.correct-hearing-event.json
      responses:
            202:
                description: OK

/hearings/{hearingId}/share-results:
  post:
      description: |
        ...
        (mapping):
            requestType: application/vnd.hearing.share-results+json
            name: hearing.share-results
        ...
      body:
        application/vnd.hearing.share-results+json:
            example: !include json/hearing.share-results.json
            schema: !include json/schema/hearing.share-results.json
      responses:
            202:
                description: OK

/application-draft-result:
  post:
      description: |
        ...
        (mapping):
            requestType: application/vnd.hearing.application-draft-result+json
            name: hearing.application-draft-result
        ...
      body:
        application/vnd.hearing.application-draft-result+json:
            example: !include json/hearing.application-draft-result.json
            schema: !include json/schema/hearing.application-draft-result.json
      responses:
            202:
                description: OK

/upload-subscriptions/{referenceDate}:
  post:
      description: |
        ...
        (mapping):
            requestType: application/vnd.hearing.upload-subscriptions+json
            name: hearing.upload-subscriptions
        ...

      body:
        application/vnd.hearing.upload-subscriptions+json:
            example: !include json/hearing.upload-subscriptions.json
            schema: !include json/schema/hearing.upload-subscriptions.json
      responses:
            202:
                description: OK

/publish-court-list:
  post:
    description: |
      Publish court list
      ...
      (mapping):
        requestType: application/vnd.hearing.publish-court-list+json
        name: hearing.publish-court-list
      ...
    body:
      application/vnd.hearing.publish-court-list+json:
        schema: !include json/schema/hearing.publish-court-list.json
        example: !include json/hearing.publish-court-list.json

    responses:
      202:
        description: Request accepted

/publishHearingListsForCrownCourts:
  post:
    description: |
      Publish hearing lists for all crown courts:
      ...
      (mapping):
        requestType: application/vnd.hearing.publish-hearing-lists-for-crown-courts+json
        name: hearing.publish-hearing-lists-for-crown-courts
      ...
    body:
      application/vnd.hearing.publish-hearing-lists-for-crown-courts+json:
        schema: !include json/schema/hearing.publish-hearing-lists-for-crown-courts.json
        example: !include json/hearing.publish-hearing-lists-for-crown-courts.json

    responses:
      202:
        description: Request accepted
/outstanding-fines:
  post:
      description: |
        ...
        (mapping):
            requestType: application/vnd.hearing.compute-outstanding-fines+json
            name: hearing.compute-outstanding-fines
        ...
      body:
        application/vnd.hearing.compute-outstanding-fines+json:
            example: !include json/hearing.compute-outstanding-fines.json
            schema: !include json/schema/hearing.compute-outstanding-fines.json
      responses:
            202:
                description: OK

/add-request-for-outstanding-fines:
  post:
    description: |
      ...
      (mapping):
          requestType: application/vnd.hearing.add-request-for-outstanding-fines+json
          name: hearing.add-request-for-outstanding-fines
      ...
    body:
      application/vnd.hearing.add-request-for-outstanding-fines+json:
            example: !include json/hearing.add-request-for-outstanding-fines.json
            schema: !include json/schema/hearing.add-request-for-outstanding-fines.json