#%RAML 0.8
title: Hearing Command handler
baseUri:  message://command/handler/message/hearing

/hearing.handler.command:
  post:
      body:
        application/vnd.hearing.initiate-hearing+json:
            example: !include json/hearing.initiate-hearing.json
            schema:  !include json/schema/hearing.initiate-hearing.json

        application/vnd.hearing.allocate-court+json:
            example: !include json/hearing.allocate-court.json
            schema:  !include json/schema/hearing.allocate-court.json

        application/vnd.hearing.book-room+json:
            example: !include json/hearing.book-room.json
            schema:  !include json/schema/hearing.book-room.json

        application/vnd.hearing.add-case+json:
            example: !include json/hearing.add-case.json
            schema:  !include json/schema/hearing.add-case.json

        application/vnd.hearing.add-prosecution-counsel+json:
            example: !include json/hearing.add-prosecution-counsel.json
            schema:  !include json/schema/hearing.add-prosecution-counsel.json

        application/vnd.hearing.add-defence-counsel+json:
            example: !include json/hearing.add-defence-counsel.json
            schema:  !include json/schema/hearing.add-defence-counsel.json

        application/vnd.hearing.create-hearing-event-definitions+json:
            example: !include json/hearing.create-hearing-event-definitions.json
            schema:  !include json/schema/hearing.create-hearing-event-definitions.json

        application/vnd.hearing.command.log-hearing-event+json:
            example: !include json/hearing.command.log-hearing-event.json
            schema: !include json/schema/hearing.command.log-hearing-event.json

        application/vnd.hearing.save-draft-result+json:
            example: !include json/hearing.save-draft-result.json
            schema: !include json/schema/hearing.save-draft-result.json

        application/vnd.hearing.command.correct-hearing-event+json:
            example: !include json/hearing.command.correct-hearing-event.json
            schema: !include json/schema/hearing.command.correct-hearing-event.json

        application/vnd.hearing.adjourn-date+json:
            example: !include json/hearing.adjourn-date.json
            schema:  !include json/schema/hearing.adjourn-date.json

        application/vnd.hearing.command.share-results+json:
            example: !include json/hearing.command.share-results.json
            schema:  !include json/schema/hearing.command.share-results.json

        application/vnd.hearing.record-confirmed-hearing+json:
            example: !include json/hearing.record-confirmed-hearing.json
            schema:  !include json/schema/hearing.record-confirmed-hearing.json

        application/vnd.hearing.command.update-plea+json:
            example: !include json/hearing.command.update-plea.json
            schema:  !include json/schema/hearing.command.update-plea.json

        application/vnd.hearing.plea-add+json:
            example: !include json/hearing.plea-add.json
            schema:  !include json/schema/hearing.plea-add.json

        application/vnd.hearing.plea-change+json:
            example: !include json/hearing.plea-change.json
            schema:  !include json/schema/hearing.plea-change.json

        application/vnd.hearing.record-sending-sheet-complete+json:
            example: !include json/hearing.record-sending-sheet-complete.json
            schema:  !include json/schema/hearing.record-sending-sheet-complete.json

        application/vnd.hearing.record-mags-court-hearing+json:
            example: !include json/hearing.record-mags-court-hearing.json
            schema:  !include json/schema/hearing.record-mags-court-hearing.json
