#%RAML 0.8
title: Private events
baseUri: message://command/handler/message/hearing
/hearing.event:
  get:
      responses:
          200:
              body:
                application/vnd.hearing.hearing-event-logged+json:
                    schema: !include json/schema/hearing.hearing-event-logged.json
                    example: !include json/hearing.hearing-event-logged.json

                application/vnd.hearing.hearing-event-deleted+json:
                    schema: !include json/schema/hearing.hearing-event-deleted.json
                    example: !include json/hearing.hearing-event-deleted.json

                application/vnd.hearing.draft-result-saved+json:
                    schema: !include json/schema/hearing.draft-result-saved.json
                    example: !include json/hearing.draft-result-saved.json

                application/vnd.hearing.hearing-event-definitions-created+json:
                    schema:  !include json/schema/hearing.hearing-event-definitions-created.json
                    example: !include json/hearing.hearing-event-definitions-created.json

                application/vnd.hearing.hearing-initiated+json:
                    schema: !include json/schema/hearing.hearing-initiated.json
                    example: !include json/hearing.hearing-initiated.json

                application/vnd.hearing.court-assigned+json:
                    schema: !include json/schema/hearing.court-assigned.json
                    example: !include json/hearing.court-assigned.json

                application/vnd.hearing.room-booked+json:
                    schema: !include json/schema/hearing.room-booked.json
                    example: !include json/hearing.room-booked.json

                application/vnd.hearing.case-associated+json:
                    schema: !include json/schema/hearing.case-associated.json
                    example: !include json/hearing.case-associated.json
